/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionPlanRouteImport } from './routes/action-plan'
import { Route as AnalyzeSoilRouteImport } from './routes/analyze-soil'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FieldMapRouteImport } from './routes/field-map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskIntelligenceRouteImport } from './routes/risk-intelligence'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanRoute = ActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeSoilRoute = AnalyzeSoilRouteImport.update({
  id: '/analyze-soil',
  path: '/analyze-soil',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldMapRoute = FieldMapRouteImport.update({
  id: '/field-map',
  path: '/field-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIntelligenceRoute = RiskIntelligenceRouteImport.update({
  id: '/risk-intelligence',
  path: '/risk-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/analyze-soil': typeof AnalyzeSoilRoute
  '/compare': typeof CompareRoute
  '/field-map': typeof FieldMapRoute
  '/reports': typeof ReportsRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/analyze-soil': typeof AnalyzeSoilRoute
  '/compare': typeof CompareRoute
  '/field-map': typeof FieldMapRoute
  '/reports': typeof ReportsRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/analyze-soil': typeof AnalyzeSoilRoute
  '/compare': typeof CompareRoute
  '/field-map': typeof FieldMapRoute
  '/reports': typeof ReportsRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plan'
    | '/analyze-soil'
    | '/compare'
    | '/field-map'
    | '/reports'
    | '/risk-intelligence'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plan'
    | '/analyze-soil'
    | '/compare'
    | '/field-map'
    | '/reports'
    | '/risk-intelligence'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/action-plan'
    | '/analyze-soil'
    | '/compare'
    | '/field-map'
    | '/reports'
    | '/risk-intelligence'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlanRoute: typeof ActionPlanRoute
  AnalyzeSoilRoute: typeof AnalyzeSoilRoute
  CompareRoute: typeof CompareRoute
  FieldMapRoute: typeof FieldMapRoute
  ReportsRoute: typeof ReportsRoute
  RiskIntelligenceRoute: typeof RiskIntelligenceRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan': {
      id: '/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof ActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze-soil': {
      id: '/analyze-soil'
      path: '/analyze-soil'
      fullPath: '/analyze-soil'
      preLoaderRoute: typeof AnalyzeSoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-map': {
      id: '/field-map'
      path: '/field-map'
      fullPath: '/field-map'
      preLoaderRoute: typeof FieldMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-intelligence': {
      id: '/risk-intelligence'
      path: '/risk-intelligence'
      fullPath: '/risk-intelligence'
      preLoaderRoute: typeof RiskIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlanRoute: ActionPlanRoute,
  AnalyzeSoilRoute: AnalyzeSoilRoute,
  CompareRoute: CompareRoute,
  FieldMapRoute: FieldMapRoute,
  ReportsRoute: ReportsRoute,
  RiskIntelligenceRoute: RiskIntelligenceRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
